[project]
name = "biodiversity-analysis-toolkit"
version = "0.1.0"
description = "Analysis tools for biodiversity research data"
authors = [
    "Tim Dennis <tdennis@library.ucla.edu>",
    "Leigh Phan <leighphan@library.ucla.edu>",
    "Reid Otsuji <rotsuji@ucsd.edu>",
    "Karla Padilla <kpadilla@ucsd.edu>"
]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[tasks]

[dependencies]
python = "*"
numpy = "*"
r = "*"
r-dplyr = "*"
